### PR TITLE
Fix finding tinyxml2 for MSYS2 if not build for PLATFORM_WINDOWS

### PR DESCRIPTION
**Pull request by R-YaTian**
Now we can build it on Windows with MSYS2 for Nintendo Switch, Nintendo 3DS and so on.

### CODE REVIEW

**Comment by Cpasjuste** [comment]
Perfect, thanks you one more time :)

**Comment by Cpasjuste** [comment]
Oups, it seems there's a problem now for compiling on linux: https://github.com/Cpasjuste/pemu/actions/runs/3195241828/jobs/5215669416
Will take a closer look later.

**Comment by R-YaTian** [comment]
> Oups, it seems there's a problem now for compiling on linux: https://github.com/Cpasjuste/pemu/actions/runs/3195241828/jobs/5215669416 Will take a closer look later.

hmmm, DISTRIB_NAME for cmake_host_system_information needs cmake 3.22 or later, I will fix it later on.

**Comment by R-YaTian** [comment]
> Oups, it seems there's a problem now for compiling on linux: https://github.com/Cpasjuste/pemu/actions/runs/3195241828/jobs/5215669416 Will take a closer look later.

Fixed via #2

**Pull request merged**
